## Test

In [1]:
print("Hello World")

Hello World

## Installing dependencies

In [4]:
pip freeze

annotated-doc==0.0.4
annotated-types==0.7.0
anyio==4.12.1
argon2-cffi==25.1.0
argon2-cffi-bindings==25.1.0
arrow==1.4.0
asttokens==3.0.1
async-lru==2.3.0
attrs==26.1.0
azure-core==1.38.2
azure-identity==1.25.2
azure-mgmt-core==1.6.0
azure-mgmt-storage==24.0.0
babel==2.18.0
beautifulsoup4==4.14.3
bleach==6.3.0
certifi==2026.2.25
cffi==2.0.0
charset-normalizer==3.4.5
click==8.3.1
colorama==0.4.6
comm==0.2.3
cryptography==46.0.5
databricks==0.2
databricks-cli==0.18.0
databricks-sdk==0.96.0
debugpy==1.8.20
decorator==5.2.1
defusedxml==0.7.1
executing==2.2.1
fastapi==0.135.1
fastjsonschema==2.21.2
fqdn==1.5.1
google-api-core==2.30.0
google-api-python-client==2.193.0
google-auth==2.48.0
google-auth-httplib2==0.3.0
google-auth-oauthlib==1.3.0
googleapis-common-protos==1.73.0
h11==0.16.0
httpcore==1.0.9
httplib2==0.31.2
httptools==0.7.1
httpx==0.28.1
idna==3.11
iniconfig==2.3.0
ipykernel==7.2.0
ipython==9.10.0
ipython_pygments_lexers==1.1.1
ipywidgets==8.1.8
isodate==0.7.2
isoduration==20.11.0
jedi==0.19.2
Jinja2==3.1.6
json5==0.14.0
jsonpointer==3.1.1
jsonschema==4.26.0
jsonschema-specifications==2025.9.1
jupyter==1.1.1
jupyter-book==2.1.2
jupyter-console==6.6.3
jupyter-events==0.12.0
jupyter-lsp==2.3.0
jupyter_client==8.8.0
jupyter_core==5.9.1
jupyter_server==2.17.0
jupyter_server_terminals==0.5.4
jupyterlab==4.5.6
jupyterlab_pygments==0.3.0
jupyterlab_server==2.28.0
jupyterlab_widgets==3.0.16
lark==1.3.1
MarkupSafe==3.0.3
matplotlib-inline==0.2.1
mistune==3.2.0
msal==1.35.1
msal-extensions==1.3.1
msrest==0.7.1
nbclient==0.10.4
nbconvert==7.17.0
nbformat==5.10.4
nest-asyncio==1.6.0
nodeenv==1.10.0
notebook==7.5.5
notebook_shim==0.2.4
numpy==2.4.4
oauthlib==3.3.1
overrides==7.7.0
packaging==26.0
pandas==3.0.2
pandocfilters==1.5.1
parso==0.8.6
platformdirs==4.9.2
pluggy==1.6.0
prometheus_client==0.24.1
prompt_toolkit==3.0.52
proto-plus==1.27.1
protobuf==6.33.5
psutil==7.2.2
pure_eval==0.2.3
py4j==0.10.9.9
pyasn1==0.6.2
pyasn1_modules==0.4.2
pycparser==3.0
pydantic==2.12.5
pydantic_core==2.41.5
Pygments==2.19.2
PyJWT==2.11.0
pyparsing==3.3.2
pyspark==4.1.1
pytest==9.0.2
python-dateutil==2.9.0.post0
python-dotenv==1.2.2
python-json-logger==4.1.0
pywinpty==3.0.3
PyYAML==6.0.3
pyzmq==27.1.0
referencing==0.37.0
requests==2.32.5
requests-oauthlib==2.0.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rfc3987-syntax==1.1.0
rpds-py==0.30.0
rsa==4.9.1
Send2Trash==2.1.0
six==1.17.0
soupsieve==2.8.3
stack-data==0.6.3
starlette==0.52.1
tabulate==0.10.0
terminado==0.18.1
tinycss2==1.4.0
tornado==6.5.4
traitlets==5.14.3
typing-inspection==0.4.2
typing_extensions==4.15.0
tzdata==2025.3
uri-template==1.3.0
uritemplate==4.2.0
urllib3==2.6.3
uvicorn==0.41.0
watchfiles==1.1.1
wcwidth==0.6.0
webcolors==25.10.0
webencodings==0.5.1
websocket-client==1.9.0
websockets==16.0
widgetsnbextension==4.0.15
Note: you may need to restart the kernel to use updated packages.

In [5]:
import sys
!{sys.executable} -m pip install seaborn matplotlib

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp311-cp311-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\shikh\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in C:\Users\shikh\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn) (3.0.2)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.62.1-cp311-cp311-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp311-cp311-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in C:\Users\shikh\AppData\Roaming\Python\Python311\site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.2.0-cp311-cp311-win_amd64.whl.metadata (9.0 kB)
Requirement already satisfied: pyparsing>=3 in C:\Users\shikh\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\shikh\AppData\Roaming\Python\Python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\shikh\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\shikh\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.10.8-cp311-cp311-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp311-cp311-win_amd64.whl (225 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp311-cp311-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp311-cp311-win_amd64.whl (73 kB)
Using cached pillow-12.2.0-cp311-cp311-win_amd64.whl (7.1 MB)
Installing collected packages: pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ---------------------------------------- 0/7 [pillow]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------------- 7/7 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.8 pillow-12.2.0 seaborn-0.13.2

## Loading libraries and data

In [32]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
dataset = pd.read_csv("messy_ml_data.csv")
dataset.head(3)

,PassengerId,Age,Fare,Gender,City,Subscription,Score,JoinDate,Email,Phone,IsActive,Remarks,DeptCode,DiscountCode
0,1,52.0,104.22,F,Tokyo,Free,55.0,2020-01-01,NaN,+1-555-8540,True,Good,D04,NaN
1,2,15.0,30.03,F,London,Premium,82.0,2020-01-02,user1@example.com,+1-555-6340,False,Average,D04,NaN
2,3,72.0,92.78,Female,New York,Basic,90.0,2020-01-03,user2@example.com,+1-555-3474,0,Poor,D02,SAVE10

In [34]:
dataset.isnull().sum()

PassengerId       0
Age              16
Fare             25
Gender           23
City             21
Subscription     26
Score            16
JoinDate         20
Email            12
Phone            26
IsActive         21
Remarks          26
DeptCode         21
DiscountCode    462
dtype: int64

# Filling or assigning missing values in a dataset = Imputation

## Wrong way of filling data to handle missing values in categorical data

In [35]:
#dataset.fillna(10).head(10)

## Correct ways of filling data to handle missing values in categorical data or time-series data

### Identify categorical data

In [36]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   761 non-null    int64
 1   Age           745 non-null    float64
 2   Fare          736 non-null    float64
 3   Gender        738 non-null    str
 4   City          740 non-null    str
 5   Subscription  735 non-null    str
 6   Score         745 non-null    float64
 7   JoinDate      741 non-null    str
 8   Email         749 non-null    str
 9   Phone         735 non-null    str
 10  IsActive      740 non-null    str
 11  Remarks       735 non-null    str
 12  DeptCode      740 non-null    str
 13  DiscountCode  299 non-null    str
dtypes: float64(3), int64(1), str(10)
memory usage: 83.4 KB

### Backfill data

In [37]:
dataset["Gender"] = dataset["Gender"].bfill()
dataset["Gender"].isnull().sum()

np.int64(0)

### Forward Fill data

In [38]:
dataset["Subscription"] = dataset["Subscription"].ffill()
dataset["Subscription"].isnull().sum()

np.int64(0)

### Forward Fill data with axis - example

In [39]:
dataset[["DeptCode", "DiscountCode"]].ffill(axis=1)

    DeptCode DiscountCode
0        D04          D04
1        D04          D04
2        D02       SAVE10
3        D04    WELCOME50
4        D01          D01
..       ...          ...
756      D02          D02
757      D03          D03
758      D03       SAVE10
759      D04          D04
760      D01       SAVE20

[761 rows x 2 columns]

### Mode Imputation

In [40]:
dataset["DiscountCode"].mode()[0]

'WELCOME50'

In [41]:
dataset["DiscountCode"] = dataset["DiscountCode"].fillna(dataset["DiscountCode"].mode()[0])
dataset["DiscountCode"]

0      WELCOME50
1      WELCOME50
2         SAVE10
3      WELCOME50
4      WELCOME50
         ...
756    WELCOME50
757    WELCOME50
758       SAVE10
759    WELCOME50
760       SAVE20
Name: DiscountCode, Length: 761, dtype: str

## Scikit learn lib for imputing

#### Finding out numerical columns

In [42]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   761 non-null    int64
 1   Age           745 non-null    float64
 2   Fare          736 non-null    float64
 3   Gender        761 non-null    str
 4   City          740 non-null    str
 5   Subscription  761 non-null    str
 6   Score         745 non-null    float64
 7   JoinDate      741 non-null    str
 8   Email         749 non-null    str
 9   Phone         735 non-null    str
 10  IsActive      740 non-null    str
 11  Remarks       735 non-null    str
 12  DeptCode      740 non-null    str
 13  DiscountCode  761 non-null    str
dtypes: float64(3), int64(1), str(10)
memory usage: 83.4 KB

In [49]:
dataset.select_dtypes(include="float64").columns

Index(['Age', 'Fare', 'Score'], dtype='str')

#### Call scikit lib

In [44]:
import sys
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\shikh\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\shikh\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\shikh\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\shikh\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\shikh\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (3.6.0)

In [45]:
from sklearn.impute import SimpleImputer

In [66]:
si = SimpleImputer(strategy="mean")
ar = si.fit_transform(dataset[['Age', 'Fare', 'Score']])
ar

array([[ 52.  , 104.22,  55.  ],
       [ 15.  ,  30.03,  82.  ],
       [ 72.  ,  92.78,  90.  ],
       ...,
       [  9.  , 320.4 ,  58.  ],
       [ 51.  , 229.23,  61.  ],
       [ 19.  , 337.36,  59.  ]], shape=(761, 3))

In [53]:
new_dataset = pd.DataFrame(ar,columns = dataset.select_dtypes(include="float64").columns)
new_dataset

      Age    Fare  Score
0    52.0  104.22   55.0
1    15.0   30.03   82.0
2    72.0   92.78   90.0
3    61.0  146.51   87.0
4    21.0   96.74   73.0
..    ...     ...    ...
756  60.0   67.70   70.0
757  57.0  450.79   82.0
758   9.0  320.40   58.0
759  51.0  229.23   61.0
760  19.0  337.36   59.0

[761 rows x 3 columns]

In [52]:
new_dataset.isnull().sum()

Age      0
Fare     0
Score    0
dtype: int64

In [58]:
dataset['Age'].isnull().sum()

np.int64(16)

In [59]:
dataset[dataset['Age'].isnull()]

,PassengerId,Age,Fare,Gender,City,Subscription,Score,JoinDate,Email,Phone,IsActive,Remarks,DeptCode,DiscountCode
71,72,NaN,149.70,F,London,Premium,NaN,01/01/2020,user71@example.com,+1-555-5236,Yes,Poor,D01,WELCOME50
79,80,NaN,204.95,Male,Tokyo,Premium,58.0,2020-03-20,user79@example.com,+1-555-5281,none,Unknown,D03,SAVE10
195,196,NaN,309.61,M,Paris,Basic,75.0,2020-07-14,user195@example.com,+1-555-1304,No,ok,D04,WELCOME50
231,232,NaN,231.59,Male,Berlin,Free,68.0,2020-08-19,user231@example.com,+1-555-3420,Yes,ok,D02,WELCOME50
274,275,NaN,325.56,F,London,Free,81.0,2020-10-01,user274@example.com,+1-555-5201,No,Poor,D04,WELCOME50
381,382,NaN,NaN,F,London,Basic,70.0,2021-01-16,user381@example.com,NaN,none,Excellent,D04,WELCOME50
399,400,NaN,77.04,M,New York,Basic,101.0,NaN,user399@example.com,+1-555-5456,1,Poor,D01,WELCOME50
459,460,NaN,206.95,female,Tokyo,Free,69.0,2021-04-04,user459@example.com,+1-555-3397,No,Excellent,D01,WELCOME50
516,517,NaN,300.54,Male,Tokyo,Basic,50.0,2021-05-31,user516@example.com,+1-555-4770,0,Good,D04,SAVE10
523,524,NaN,478.27,female,Paris,Premium,97.0,NaN,user523@example.com,+1-555-9980,none,Unknown,D04,SAVE10
528,529,NaN,NaN,male,Tokyo,Basic,82.0,2021-06-12,user528@example.com,+1-555-3152,none,Average,D02,WELCOME50
545,546,NaN,287.21,F,Tokyo,Basic,81.0,2021-06-29,user545@example.com,+1-555-9858,NaN,Good,D03,SAVE10
574,575,NaN,319.59,male,NaN,Basic,90.0,2021-07-28,user574@example.com,+1-555-2120,True,Poor,D01,WELCOME50
626,627,NaN,215.67,male,Paris,Free,56.0,2021-09-18,user626@example.com,+1-555-1561,False,ok,D02,SAVE20
673,674,NaN,431.46,Female,Tokyo,Premium,64.0,2021-11-04,user673@example.com,+1-555-7815,0,Average,D03,SAVE20
705,706,NaN,NaN,M,Paris,Basic,72.0,2021-12-06,user705@example.com,+1-555-2659,Yes,Average,D03,WELCOME50

In [60]:
dataset[dataset['Age'].isnull()].index.tolist()

[71, 79, 195, 231, 274, 381, 399, 459, 516, 523, 528, 545, 574, 626, 673, 705]

In [62]:
new_dataset["Age"][[71, 79, 195, 231, 274, 381, 399, 459, 516, 523, 528, 545, 574, 626, 673, 705]]

71     41.885906
79     41.885906
195    41.885906
231    41.885906
274    41.885906
381    41.885906
399    41.885906
459    41.885906
516    41.885906
523    41.885906
528    41.885906
545    41.885906
574    41.885906
626    41.885906
673    41.885906
705    41.885906
Name: Age, dtype: float64

In [63]:
indices = dataset[dataset['Age'].isnull()].index.tolist()
new_dataset.loc[indices, "Age"]

71     41.885906
79     41.885906
195    41.885906
231    41.885906
274    41.885906
381    41.885906
399    41.885906
459    41.885906
516    41.885906
523    41.885906
528    41.885906
545    41.885906
574    41.885906
626    41.885906
673    41.885906
705    41.885906
Name: Age, dtype: float64

#### Insert the valules into the original dataset

In [67]:
cols_to_fill = ['Age', 'Fare', 'Score']
dataset[cols_to_fill] = ar
print(dataset[cols_to_fill].isnull().sum())

Age      0
Fare     0
Score    0
dtype: int64

In [68]:
dataset.isnull().sum()

PassengerId      0
Age              0
Fare             0
Gender           0
City            21
Subscription     0
Score            0
JoinDate        20
Email           12
Phone           26
IsActive        21
Remarks         26
DeptCode        21
DiscountCode     0
dtype: int64